[package]
name = "rust_pipeline_demo"
version = "0.1.0"
edition = "2024"
description = "Projet de d√©monstration pour pipeline CI/CD Jenkins"
authors = ["pipeline-demo"]

[[bin]]
name = "rust_pipeline_demo"
path = "src/main.rs"

[lib]
name = "rust_pipeline_demo"
path = "src/lib.rs"

[dependencies]
